---
- name: Install Docker and Configure User
  hosts: almalinux_hosts
  become: true # Most tasks require root (sudo) privileges

  tasks:
    - name: 1. Install required system packages
      ansible.builtin.dnf:
        name:
          - dnf-utils
          - yum-utils
        state: present

    - name: 2. Add Docker CE repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: 3. Install Docker Engine
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest # Ensures the latest version is installed
        update_cache: true

    - name: 4. Start and enable the Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: 5. Add the current Ansible user to the 'docker' group
      ansible.builtin.user:
        name: "{{ ansible_user }}" # A fact that holds the username Ansible connected with
        groups: docker
        append: yes
      register: user_group_change

    # This meta task is crucial. It forces Ansible to reset its connection.
    # Without this, the new group membership for the user will not be active
    # for any subsequent tasks in the same playbook run.
    - name: 6. Reset SSH connection to apply group membership
      ansible.builtin.meta: reset_connection
      when: user_group_change.changed