---
- name: 🧪 VÉRIFICATION DE LA COMPATIBILITÉ AVEC LA DETTE TECHNIQUE
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: 1. Confirmer l'interpréteur de l'EE (Moteur)
      ansible.builtin.command: /usr/bin/python --version
      register: ee_python_check
      changed_when: false

    - name: Afficher le moteur d'exécution (Python 3.x)
      ansible.builtin.debug:
        msg: "✅ Moteur d'exécution EE (localhost) : {{ ee_python_check.stdout | trim }}"

    - name: 2. Confirmer la version d'Ansible (2.9.27)
      ansible.builtin.command: ansible-playbook --version
      register: ansible_version_check
      changed_when: false

    - name: Confirmer la version d'Ansible Runner (2.3.2)
      ansible.builtin.command: ansible-runner --version
      register: runner_version_check
      changed_when: false

    - name: Afficher les versions validées
      ansible.builtin.debug:
        msg: |
          "--- RÉSULTATS DE L'EE ---
          Ansible Version: {{ ansible_version_check.stdout_lines[0] | regex_replace('.*([0-9]+\\.[0-9]+\\.[0-9]+).*', '\\1') }}
          Ansible Runner Version: {{ runner_version_check.stdout_lines[0] | trim }} (Compatible AWX)
          "
      failed_when: "'2.9.27' not in ansible_version_check.stdout"

# --------------------------------------------------------------------------------------
- name: 🚀 TESTER LE RÔLE SUR LA CIBLE ANCIENNE (CentOS 7 / Python 2.7.5)
  hosts: ee_test # Hôtes avec Python 2.7
  gather_facts: false

  tasks:
    - name: 3. Tester la connexion et vérifier l'interpréteur sur l'hôte cible
      # Ansible utilise ici l'interpréteur /usr/bin/python de l'hôte cible (qui est Python 2.7.5)
      ansible.builtin.command: /usr/bin/python -V
      register: target_python_check

    - name: Afficher l'interpréteur de la cible
      ansible.builtin.debug:
        msg: "✅ Interpréteur de la cible : {{ target_python_check.stderr | trim }} (Validation Python 2.7.x)"

    - name: 4. Exécuter un module Ansible 2.9 (yum)
      ansible.builtin.yum:
        name: httpd
        state: present
      register: yum_result

    - name: Confirmer le succès sur la cible
      ansible.builtin.debug:
        msg: "✅ Test de Playbook 2.9 réussi sur cible ancienne."