---
- name: 🧪 VÉRIFICATION DE L'EE ANSIBLE (LOCALHOST)
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: 1. Vérifier la version d'Ansible (doit être 2.9.13)
      # Utilisation du binaire ansible-playbook pour vérifier la version installée dans l'EE
      ansible.builtin.command: ansible-playbook --version
      register: ansible_version_check
      changed_when: false

    - name: Afficher la version d'Ansible
      ansible.builtin.debug:
        msg: "✅ Version d'Ansible trouvée: {{ ansible_version_check.stdout_lines[0] | regex_replace('.*([0-9]+\\.[0-9]+\\.[0-9]+).*', '\\1') }}"

    - name: 2. Vérifier l'interpréteur Python de l'EE (pour confirmation 2.7.5)
      # Utiliser 'which python' pour trouver le chemin, puis vérifier la version.
      ansible.builtin.command: which python
      register: python_path_check
      changed_when: false

    - name: 3. Afficher et valider la version de Python
      ansible.builtin.command: "{{ python_path_check.stdout | trim }} -V"
      register: python_version_check
      changed_when: false

    - name: Afficher la version de Python
      ansible.builtin.debug:
        msg: "✅ Version de Python de l'EE: {{ python_version_check.stderr | trim }}"

    - name: 4. Test d'un module basique (file) dans l'EE
      # Cette tâche DOIT cibler localhost car c'est un test de la capacité de l'EE.
      ansible.builtin.file:
        path: /tmp/ee_test_ansible_29.txt
        state: touch
        mode: '0644'
      delegate_to: localhost
      register: file_result

    - name: Confirmer le succès du module 'file'
      ansible.builtin.debug:
        msg: "✅ Module 'file' (Ansible 2.9) testé avec succès dans l'EE."