---
- name: 🧪 VÉRIFICATION DE L'EE ANSIBLE 2.9.13 / PYTHON 2.7.5
  hosts: localhost
  connection: local
  gather_facts: false # Désactiver la collecte de faits pour éviter l'erreur initiale

  tasks:
    - name: 1. Définir l'interpréteur Python pour localhost (EE)
      # Bien que connection: local soit utilisé, ceci peut aider à stabiliser
      # l'environnement pour les sous-processus.
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python

    - name: 2. Vérifier la version d'Ansible (doit être 2.9.13)
      # Utiliser la commande 'ansible --version' exécutée localement.
      ansible.builtin.command: ansible --version
      register: ansible_version_check
      changed_when: false

    - name: Afficher et valider la version d'Ansible
      ansible.builtin.debug:
        msg: "✅ Version d'Ansible: {{ ansible_version_check.stdout_lines[0] | regex_replace('.*([0-9]+\\.[0-9]+\\.[0-9]+).*', '\\1') }}"
      # Vérification optionnelle pour s'assurer que c'est 2.9.13
      # failed_when: "'2.9.13' not in ansible_version_check.stdout"

    - name: 3. Vérifier la version de Python (doit être 2.7.5)
      # Utiliser la commande 'python -V' exécutée localement.
      ansible.builtin.command: python -V
      register: python_version_check
      changed_when: false

    - name: Afficher et valider la version de Python
      # Python -V affiche sur stderr
      ansible.builtin.debug:
        msg: "✅ Version de Python dans l'EE: {{ python_version_check.stderr | trim }}"
      # Vérification optionnelle pour s'assurer que c'est 2.7
      # failed_when: "'Python 2.7' not in python_version_check.stderr"

    - name: 4. Tester un module intégré d'Ansible 2.9 (file)
      # Utilise le module 'file' sur le conteneur EE.
      ansible.builtin.file:
        path: /tmp/ee_test_ansible_29.txt
        state: touch
        mode: '0644'
      delegate_to: localhost
      register: file_result

    - name: Confirmer le succès du module 'file'
      ansible.builtin.debug:
        msg: "✅ Module 'file' (Ansible 2.9) testé avec succès. Changement: {{ file_result.changed }}"

# ---
- name: 🚀 TEST DE DÉPLOIEMENT SUR UNE CIBLE CENTOS 7
  hosts: ee_test # Remplacer par le groupe/hôte cible dans votre inventaire AWX
  gather_facts: false

  tasks:
    - name: 5. Assurer l'utilisation de Python 2.7 sur l'hôte cible
      # Le système CentOS 7 utilise Python 2.7 par défaut, spécifions-le explicitement.
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python

    - name: 6. Tester un module spécifique à CentOS 7 (yum)
      # 'yum' est le gestionnaire de paquets standard sous CentOS 7.
      ansible.builtin.yum:
        name: wget
        state: present
      register: yum_result

    - name: Confirmer le succès du module 'yum'
      ansible.builtin.debug:
        msg: "✅ Module 'yum' (Ansible 2.9) testé avec succès sur l'hôte cible. Changement: {{ yum_result.changed }}"