all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 172.17.0.3
        web02:
          ansible_host: 172.17.0.4
    databases:
      hosts:
        db01:
          ansible_host: 172.17.0.5