---
collections:
  - name: community.postgresql
    version: "4.1.0" # Utilisez la version stable souhaitée

  # Ajout de la collection contenant 'profile_tasks'
  - name: ansible.posix
    version: "1.5.4" # Utilisez la version stable souhaitée