version: 1

images:
  base_image:
    name: docker-systemd:centos-7

dependencies:
  python: requirements.txt

options:
  package_manager_path: /usr/bin/yum

additional_build_steps:
  prepend_base:
    - RUN yum install -y epel-release
    - RUN yum install -y python2 python2-pip python36 python36-pip gcc python2-devel rust
    - RUN ln -s /usr/bin/python2 /usr/bin/python || true
    - RUN ln -s /usr/bin/python3.6 /usr/bin/python3 || true

    # Vérifier les versions initiales
    - RUN python2 -m pip --version || true
    - RUN python3 -m pip --version || true

    - RUN localedef -i en_US -f UTF-8 en_US.UTF-8 || true
    - ENV LANG=en_US.UTF-8
    - ENV LC_ALL=en_US.UTF-8

    # Installer des versions spécifiques et compatibles Python 2
    - RUN python2 -m pip install pip==20.3.4 setuptools==44.1.1 wheel==0.36.2
    - RUN python3 -m pip install pip==21.3.1 setuptools==58.0.4 wheel==0.37.1

    # Installer Ansible et Runner compatibles
    - RUN python2 -m pip install ansible==2.9.13 ansible-runner==1.3.4
    - RUN python3 -m pip install ansible==2.9.13 ansible-runner==1.4.6

    # (optionnel) eviter des dépendances modernes comme cryptography>3.4
    - RUN python2 -m pip install "cryptography<3.4"
    - RUN python3 -m pip install "cryptography<3.4"

    # Installer Ansible + ansible-runner dans les deux versions
    - RUN python2 -m pip install ansible==2.9.13 ansible-runner==1.3.4
    - RUN python3 -m pip install ansible==2.9.13 ansible-runner==1.4.6

    - RUN mkdir -p /etc/ansible